/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team14.server;

import java.io.IOException;
import edu.duke.ece651.team14.shared.MyName;

public class App {
  ServerAdmin serverAdmin;
  int num_players;

  public App(int portNum, int num_players) throws IOException {
    this.serverAdmin = new ServerAdmin(portNum);
    this.num_players = num_players;
  }

  public String getMessage() {
    return "Hello from the server for " + MyName.getName();
  }

  public void startGame() throws IOException {
    try {
      serverAdmin.acceptPlayersPhase(num_players);
      serverAdmin.InitializeGamePhase();
    } finally {
      serverAdmin.releaseResources();
    }
    System.out.println("done");
  }

  // ./gradlew :server:run --args "[portnum] [num_players]"
  public static void main(String[] args) throws IOException {
    int port = Integer.parseInt(args[0]);
    int num_players = Integer.parseInt(args[1]);
    App a = new App(port, num_players);
    System.out.println(a.getMessage());
    a.startGame();
  }
}
