/*
This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team14.server;

import java.io.IOException;

public class App {
  ServerAdmin serverAdmin;

  /**
   * Constructor
   *
   * @param portNum:     server port number
   * @throws IOException
   */
  public App(int portNum) throws IOException {
    if (portNum != 4444) {
      throw new IllegalArgumentException("Use port 4444 to run RISC server.");
    }
    this.serverAdmin = new ServerAdmin(portNum);
  }

  protected void startServer(){
    this.serverAdmin.ServerHandleRequest();
  }
  
  // ./gradlew :server:run --args "[portnum]"
  public static void main(String[] args) throws IOException, ClassNotFoundException {
    try {
      int port = Integer.parseInt(args[0]);
      App a = new App(port);
      System.out.println("Welcome to the RISC server terminal\n");
      a.startServer();
    } catch (Exception e) {
      System.out.println("\nError detected: " + e.getMessage());
      System.out.println("Exiting...");
    }
  }
}
